name: Standard Issue
description: A simple template for creating standard issues.

body:
  - type: markdown
    attributes:
      value: |
        ## Description
        _Provide a short summary of the issue here._

  - type: textarea
    id: issue-description
    attributes:
      label: Description
      description: Provide details about the issue.
      placeholder: Short summary of the issue.

  - type: markdown
    attributes:
      value: |
        ## Acceptance Criteria

  - type: checkboxes
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      options:
        - label: Criteria 1
        - label: Criteria 2
        - label: Criteria 3
