name: Standard Issue
description: A simple template for creating standard issues.

body:
  - type: textarea
    id: issue-description
    attributes:
      label: Description
      description: Provide details about the issue.
      placeholder: Short summary of the issue.
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Provide criteria that have to be met before closing this issue.
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Add any extra thoughts, links, or information.
      placeholder: Optional notes or context.
    validations:
      required: false
